# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='workers',
        ),
        migrations.AddField(
            model_name='job',
            name='worker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='planned_job', to='login_app.User'),
            preserve_default=False,
        ),
    ]
