# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180821_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='worker',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planned_job', to='login_app.User'),
            preserve_default=False,
        ),
    ]
